name: avr-gcc compilation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [ '1.6.12', 'devel' ]
    name: Nim ${{ matrix.nim }} compilation
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - name: Install avr-gcc
        run: |
          sudo apt-get update
          sudo apt-get install avr-libc gcc-avr
      - name: Build setp
        run: make
