# https://github.com/marketplace/actions/avr-make
name: avr-gcc compilation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [ '1.6.12', 'devel' ]
    name: Nim ${{ matrix.nim }} compilation
    steps:
      - uses: actions/checkout@master
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - name: Install avr-gcc
        run: |
          sudo apt-get update
          sudo apt-get install avr-libc gcc-avr
      - run: make
